import type { NextPage } from 'next'
import Head from 'next/head'
import EyeG1 from '../AsetG/Component/EyeG1/EyeG1'

const Home: NextPage = () => {
  return (    
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0"></meta>
        <link rel="icon" href="/favicon.ico" />
      </Head>  
      <EyeG1/>
    </>  
  )
}

export default Home
